# This is similar to the default template provided by gitlab.
# The only difference is the image, in order to ensure compatibility with go modules.

image:
  name: klakegg/hugo:edge-ext-alpine
  entrypoint: [""]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo
  except:
    - master

pages:
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master